version: '3'
services:
  linksave:
    container_name: linksavehost
    image: linksavehost-img
    build: .
    ports:
    - "8080:8080"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - linksavehost-img

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom/prometheus

  client:
    container_name: linksave-client
    image: linksave-client-img
    build: ./client/
    ports:
      - "3030:3030"
    depends_on:
      - linksavehost-img

