version: '3.7'
services:
  linksave:
    build: .
    ports:
    - "8080:8080"
    container_name: linksavehost

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    container_name: grafana
